/* automatically generated by rust-bindgen */

#![allow(dead_code)]
use anonify_types::*;
use sgx_types::*;

extern "C" {
    pub fn ecall_get_state(
        eid: sgx_enclave_id_t,
        retval: *mut sgx_status_t,
        sig: *mut [u8; 65usize],
        msg: *mut [u8; 32usize],
        state: *mut u64,
    ) -> sgx_status_t;
}
