[package]
name = "erc20-enclave"
version = "0.5.4"
authors = ["LayerX Labs <div-labs@layerx.co.jp>"]
edition = "2018"

[lib]
name = "anonifyenclave"
crate-type = ["staticlib"]

[dependencies]
frame-runtime = { path = "../../../frame/runtime", default-features = false, features = ["sgx"] }
frame-config = { path = "../../../frame/config", default-features = false, features = ["sgx"] }
frame-enclave = { path = "../../../frame/enclave", default-features = false }
frame-sodium = { path = "../../../frame/sodium", default-features = false, features = ["sgx"] }
frame-types = { path = "../../../frame/types" }
frame-common = { path = "../../../frame/common", default-features = false, features = ["sgx"] }
anonify-enclave = { path = "../../../modules/anonify-enclave", default-features = false }
anonify-ecall-types = { path = "../../../modules/anonify-ecall-types", default-features = false, features = ["sgx"] }
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git"}
ed25519-dalek = { version = "1.0.0-pre.2", default-features = false, features = ["u64_backend"] }
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
anyhow = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/anyhow-sgx.git" }
lazy_static = { version = "1.4", features = ["spin_no_std"] }
bincode = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/bincode-sgx" }
env_logger = { git = "https://github.com/mesalock-linux/env_logger-sgx", default-features = false, features = ["mesalock_sgx"] }
log = { git = "https://github.com/mesalock-linux/log-sgx" }

[features]
default = ["backup-enable", "runtime_enabled", "enclave_key", "verify-mr-enclave-enable"]
backup-enable = ["anonify-enclave/backup-enable"]
runtime_enabled = []
enclave_key = []
treekem = []
verify-mr-enclave-enable = [
    "frame-runtime/verify-mr-enclave-enable",
    "frame-enclave/verify-mr-enclave-enable",
    "anonify-enclave/verify-mr-enclave-enable",
    "anonify-ecall-types/verify-mr-enclave-enable",
]