[package]
name = "frame-mra-tls"
version = "0.5.4"
authors = ["LayerX Labs <div-labs@layerx.co.jp>"]
edition = "2018"

[dependencies]
remote-attestation = { path = "../remote-attestation", default-features = false, features = ["sgx"] }
frame-retrier = { path = "../retrier", default-features = false, features = ["sgx"]}
frame-config = { path = "../config", default-features = false, features = ["sgx"]}
frame-sodium = { path = "../sodium", default-features = false, features = ["sgx"]}
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net", "backtrace", "thread"] }
sgx_tcrypto = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
rustls = { branch = "mesalock_sgx", version = "^0.19", git = "https://github.com/mesalock-linux/rustls", features = ["dangerous_configuration"] }
anyhow = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/anyhow-sgx.git" }
thiserror = { git = "https://github.com/mesalock-linux/thiserror-sgx.git" }
serde_json = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/serde-json-sgx" }
serde = { git = "https://github.com/mesalock-linux/serde-sgx.git" } # Don't specify version due to serde_json dependency
serde_bytes = { git = "https://github.com/mesalock-linux/serde-bytes-sgx" }
http = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/http-sgx" }
webpki = { branch = "mesalock_sgx", git = "https://github.com/mesalock-linux/webpki" } # Specify branch name due to rustls dependency
webpki-roots = { branch = "mesalock_sgx", git = "https://github.com/mesalock-linux/webpki-roots" }
lazy_static = { version = "1.4", features = ["spin_no_std"] }
yasna = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/yasna.rs-sgx", features = ["bit-vec", "num-bigint", "chrono"] }
bit-vec = { version = "0.6.1", default-features = false }
num-bigint = { version = "0.2", git = "https://github.com/mesalock-linux/num-bigint-sgx" }
chrono = { version = "0.4", git = "https://github.com/mesalock-linux/chrono-sgx" }
test-utils = { path = "../../tests/utils", default-features = false, features = ["sgx"] }
pem = { version = "0.8.2", git = "https://github.com/mesalock-linux/pem-rs-sgx" }
tracing = { version = "0.1", default-features = false }
log = { git = "https://github.com/mesalock-linux/log-sgx" }

[features]
default = ["verify-mr-enclave-enable"]
verify-mr-enclave-enable = []