[package]
name = "erc20-server"
version = "0.5.4"
authors = ["LayerX Labs <div-labs@layerx.co.jp>"]
edition = "2018"

[dependencies]
state-runtime-node-server = { path = "../../../nodes/state-runtime/server", default-features = false }
anonify-eth-driver = { path = "../../../modules/anonify-eth-driver", default-features = false }
frame-host = { path = "../../../frame/host" }
actix-web = "3"
failure = "0.1"
tracing-subscriber = "0.2"
actix-web-opentelemetry = "0.9"
opentelemetry-jaeger = { version = "0.10", features = ["tokio"] }
tracing-opentelemetry = "0.10"

[features]
default = ["std", "backup-enable", "verify-mr-enclave-enable"]
std = [
    "anonify-eth-driver/std",
]
backup-enable = [
    "state-runtime-node-server/backup-enable",
    "anonify-eth-driver/backup-enable",
]
verify-mr-enclave-enable = [
    "state-runtime-node-server/verify-mr-enclave-enable",
    "anonify-eth-driver/verify-mr-enclave-enable",
]