[package]
name = "frame-treekem"
version = "0.5.4"
authors = ["LayerX Labs <div-labs@layerx.co.jp>"]
edition = "2018"

[dependencies]
frame-config = { path = "../config", default-features = false, features = ["sgx"] }
frame-common = { path = "../common", default-features = false, features = ["sgx"] }
frame-mra-tls = { path = "../../frame/mra-tls", default-features = false }
test-utils = { path = "../../tests/utils", default-features = false, features = ["sgx"] }
hex = { version = "0.4", default-features = false }
anyhow = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/anyhow-sgx.git" }
libsecp256k1 = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/libsecp256k1-rs-sgx" }
rand = { rev = "v0.7.3_sgx1.1.3", git = "https://github.com/mesalock-linux/rand-sgx" }
rand_core = { rev = "v0.7.3_sgx1.1.3", git = "https://github.com/mesalock-linux/rand-sgx" }
ring = { git = "https://github.com/mesalock-linux/ring-sgx", tag = "v0.16.5" }
tracing = { version = "0.1", default-features = false }
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net", "backtrace"] }
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tseal = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
serde = { git = "https://github.com/mesalock-linux/serde-sgx.git", default-features = false, features = ["derive"] }
serde_json = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/serde-json-sgx" }
bincode = { git = "https://github.com/mesalock-linux/bincode-sgx" }
serde_bytes = { git = "https://github.com/mesalock-linux/serde-bytes-sgx" }
base64 = { rev = "sgx_1.1.3", git = "https://github.com/mesalock-linux/rust-base64-sgx" }

[features]
default = ["backup-enable", "verify-mr-enclave-enable"]
backup-enable = []
verify-mr-enclave-enable = []