[package]
name = "state-runtime-node-server"
version = "0.5.4"
authors = ["LayerX Labs <div-labs@layerx.co.jp>"]
edition = "2018"

[dependencies]
state-runtime-node-api = { path = "../api" }
anonify-ecall-types = { path = "../../../modules/anonify-ecall-types"}
anonify-eth-driver = { path = "../../../modules/anonify-eth-driver", default-features = false }
frame-host = { path = "../../../frame/host" }
frame-common = { path = "../../../frame/common" }
frame-config = { path = "../../../frame/config" }
sgx_types = "1.1.1"
actix-web = "4.0.0-beta.1"
actix-rt = "2.2"
failure = "0.1"
tracing = "0.1"
tracing-subscriber = "0.2"
hex = "0.4"
anyhow = "1.0"
web3 = "0.14"
serde_json = "1.0"
thiserror = "1.0"
tracing-futures = "0.2.5"
opentelemetry = { version = "0.11", features = ["metrics", "tokio"] }
tracing-opentelemetry = "0.10"

[dev-dependencies]
integration-tests = { path = "../../../tests/integration" }
frame-sodium = { path = "../../../frame/sodium" }
rand_core = "0.5"
rand = "0.7"
test-utils = { path = "../../../tests/utils" }
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-core = "0.1"

[features]
default = ["backup-enable"]
backup-enable = [
    "anonify-eth-driver/backup-enable",
]
