/* automatically generated by rust-bindgen */

#![allow(dead_code)]
use anonify_types::*;
use sgx_types::*;

extern "C" {
    pub fn ocall_sgx_init_quote(
        retval: *mut sgx_status_t,
        ret_ti: *mut sgx_target_info_t,
        ret_gid: *mut sgx_epid_group_id_t,
    ) -> sgx_status_t;
}
extern "C" {
    pub fn ocall_get_quote(
        retval: *mut sgx_status_t,
        p_sigrl: *const u8,
        sigrl_len: u32,
        report: *const sgx_report_t,
        quote_type: sgx_quote_sign_type_t,
        p_spid: *const sgx_spid_t,
        p_nonce: *const sgx_quote_nonce_t,
        p_qe_report: *mut sgx_report_t,
        p_quote: *mut sgx_quote_t,
        maxlen: u32,
        p_quote_len: *mut u32,
    ) -> sgx_status_t;
}
extern "C" {
    pub fn ocall_get_ias_socket(
        retval: *mut sgx_status_t,
        ret_fd: *mut ::std::os::raw::c_int,
    ) -> sgx_status_t;
}
extern "C" {
    pub fn ocall_save_to_memory(
        retval: *mut u64,
        data_ptr: *const u8,
        data_len: usize,
    ) -> sgx_status_t;
}
extern "C" {
    pub fn ocall_get_update_info(
        retval: *mut sgx_status_t,
        platformBlob: *mut sgx_platform_info_t,
        enclaveTrusted: i32,
        update_info: *mut sgx_update_info_bit_t,
    ) -> sgx_status_t;
}
