[package]
name = "anonify-eth-driver"
version = "0.5.4"
authors = ["LayerX Labs <div-labs@layerx.co.jp>"]
edition = "2018"

[dependencies]
frame-types = { path = "../../frame/types" }
frame-common = { path = "../../frame/common" }
frame-sodium = { path = "../../frame/sodium" }
frame-runtime = { path = "../../frame/runtime", default-features = false }
frame-host = { path = "../../frame/host" }
frame-retrier = { path = "../../frame/retrier" }
frame-config = { path = "../../frame/config" }
anonify-ecall-types = { path = "../anonify-ecall-types", default-features = false }
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
thiserror = "1.0"
anyhow = "1.0"
ed25519-dalek = "1.0.0-pre.2"
parking_lot = "0.10"
web3 = "0.14"
ethabi = "12.0.0"
hex = "0.4"
tracing = "0.1"
serde_json = "1.0"
bincode = "1.3"
actix-rt = "1.1"
once_cell = "1.5"
opentelemetry = { version = "0.11", features = ["metrics", "tokio"] }
tracing-opentelemetry = "0.10"
tracing-futures = "0.2.5"

[features]
default = ["backup-enable", "verify-mr-enclave-enable"]
backup-enable = []
verify-mr-enclave-enable = [
    "frame-runtime/verify-mr-enclave-enable",
    "anonify-ecall-types/verify-mr-enclave-enable",
]