/* automatically generated by rust-bindgen */

#![allow(dead_code)]
use anonify_types::*;
use sgx_types::*;

extern "C" {
    pub fn ecall_insert_ciphertext(
        eid: sgx_enclave_id_t,
        retval: *mut sgx_status_t,
        ciphertexts: *mut u8,
        ciphertexts_len: usize,
        enclave_kv: *mut RawUpdatedState,
    ) -> sgx_status_t;
}
extern "C" {
    pub fn ecall_insert_handshake(
        eid: sgx_enclave_id_t,
        retval: *mut sgx_status_t,
        handshake: *mut u8,
        handshake_len: usize,
    ) -> sgx_status_t;
}
extern "C" {
    pub fn ecall_get_state(
        eid: sgx_enclave_id_t,
        retval: *mut sgx_status_t,
        sig: *mut [u8; 64usize],
        pubkey: *mut [u8; 32usize],
        challenge: *mut [u8; 32usize],
        mem_id: u32,
        state: *mut EnclaveState,
    ) -> sgx_status_t;
}
extern "C" {
    pub fn ecall_instruction(
        eid: sgx_enclave_id_t,
        retval: *mut sgx_status_t,
        sig: *mut [u8; 64usize],
        pubkey: *mut [u8; 32usize],
        challenge: *mut [u8; 32usize],
        state: *mut u8,
        state_len: usize,
        state_id: u64,
        call_id: u32,
        result: *mut RawInstructionTx,
    ) -> sgx_status_t;
}
extern "C" {
    pub fn ecall_join_group(
        eid: sgx_enclave_id_t,
        retval: *mut sgx_status_t,
        result: *mut RawJoinGroupTx,
    ) -> sgx_status_t;
}
extern "C" {
    pub fn ecall_handshake(
        eid: sgx_enclave_id_t,
        retval: *mut sgx_status_t,
        result: *mut RawHandshakeTx,
    ) -> sgx_status_t;
}
extern "C" {
    pub fn ecall_register_notification(
        eid: sgx_enclave_id_t,
        retval: *mut sgx_status_t,
        sig: *mut [u8; 64usize],
        pubkey: *mut [u8; 32usize],
        challenge: *mut [u8; 32usize],
    ) -> sgx_status_t;
}
extern "C" {
    pub fn ecall_run_tests(eid: sgx_enclave_id_t) -> sgx_status_t;
}
