[package]
name = "key-vault-node-server"
version = "0.5.4"
authors = ["LayerX Labs <div-labs@layerx.co.jp>"]
edition = "2018"

[dependencies]
actix-web = "4.0.0-beta.1"
anyhow = "1.0"
sgx_types = "1.1.1"
tracing = "0.1"
tracing-subscriber = "0.2"
key-vault-host = { path = "../../modules/key-vault-host" }

[dev-dependencies]
frame-host = { path = "../../frame/host" }
frame-config = { path = "../../frame/config" }
frame-common = { path = "../../frame/common" }
frame-sodium = { path = "../../frame/sodium" }
anonify-eth-driver = { path = "../../modules/anonify-eth-driver" }
state-runtime-node-server = { path = "../../nodes/state-runtime/server" }
state-runtime-node-api = { path = "../../nodes/state-runtime/api" }
test-utils = { path = "../../tests/utils" }
actix-rt = "2.2"
serde_json = "1.0"
once_cell = "1.5.2"
web3 = "0.14"
sgx_urts = "1.1.1"
rand_core = "0.5"
rand = "0.7"
tracing-core = "0.1"
